name: CI

on:
  pull_request:
  push:
    branches:
      - main
    paths-ignore:
      - README.md

permissions:
  contents: read
  id-token: write

jobs:
  debian:
    name: Deb packages
    runs-on: ubuntu-latest
    steps:
      - name: Make deb packages
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile
          pull: true
          outputs: pkgs
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: etcd-pkgs
          path: pkgs
      - name: Upload deb packages to Packagecloud
        if: github.ref == 'refs/heads/main'
        run: |
          set -eux
          for PKG_FILE in $(find pkgs -name "*.deb")
          do
            curl -fsS -u "${{ secrets.PACKAGECLOUD_TOKEN }}:" -XPOST \
              -F "package[distro_version_id]=35" \
              -F "package[package_file]=@${PKG_FILE}" \
              https://packagecloud.io/api/v1/repos/84codes/etcd/packages.json
           done
